CREATE TABLE YourLibrary.BALANCETAB (
            TRANSTYPE CHAR(1) NOT NULL,
            AMOUNT DECIMAL(15, 5) NOT NULL,
            TRANSTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (TRANSTIME)
        )
    RCDFMT BAL; 
