CREATE OR REPLACE PROCEDURE YourLibrary.GETBALANCE (
    OUT BALANCE DECIMAL(15, 2)
)
NOT DETERMINISTIC
BEGIN
    SET BALANCE = 
    COALESCE((SELECT SUM(AMOUNT) FROM YourLibrary.BALANCETAB WHERE TRANSTYPE = 'D'), 0)
    –
    COALESCE((SELECT SUM(AMOUNT) FROM YourLibrary.BALANCETAB WHERE TRANSTYPE = 'W'), 0);
END;
