CREATE PROCEDURE YourLibrary.GETBALANCE ( 
	OUT BALANCE DECIMAL(15, 5) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC YourLibrary.GETBALANCE 
	NOT DETERMINISTIC  
	BEGIN 
  
SELECT 
( COALESCE ( ( SELECT SUM ( AMOUNT ) FROM YourLibrary.BALANCETAB WHERE TRANSTYPE = 'D' ) , 0 ) - 
COALESCE ( ( SELECT SUM ( AMOUNT ) FROM YourLibrary.BALANCETAB WHERE TRANSTYPE = 'W' ) , 0 ) ) 
INTO BALANCE 
FROM SYSIBM.SYSDUMMY1 ; 
  
END  ; 
