CREATE PROCEDURE YourLibrary.PROCESSTRANSACTION (
  IN AMOUNT DECIMAL(15, 2),
  IN TTYPE CHAR(1),
  OUT BALANCE DECIMAL(15, 2),
  OUT MESSAGE CHAR(35)
)
LANGUAGE RPGLE
MODIFIES SQL DATA
EXTERNAL NAME 'YourLibrary/TRANSACT'
PARAMETER STYLE GENERAL;
  
